#        Inside the role, you should have tasks that:
#        DONE * Configure the nginx to serve a static webpage.
#        DONE * Ensure the necessary directories are present for the webpage.
#        DONE * Copy a sample index.html to the appropriate directory on the server.
#        * Update your role tasks to use the template module to generate the index.html page from a template, replacing some content with the web_page_content variable.
---
# tasks file for nginx_setup
 - name: (NGINX) Install Nginx Web server
   package:
     name: "{{ item }}"
     state: latest
   with_items:
     - nginx

- name: Start and enable the nginx service
  service: 
  name: nginx
  enabled: yes
  state: started

- name: Copy sample index file to the appropriate directory on the server
  copy:
   src: /srv/myfiles/sample.index.html
   dest: /var/web/html/index.html

- name: Use template module to generate index.html from a template, replacing some content with the web_page_content variable
