#    4) _Using Variables_:
#        Create a _vars/main.yml_ file inside the _nginx_setup_ role.
#        Define a variable named _web_page_content_ and assign some HTML content to it.
#        Update your role tasks to use the template module to generate the index.html page from a template, replacing some content with the web_page_content variable.
---
# tasks file for nginx_setup
