#        Inside the role, you should have tasks that:
#        * Configure the nginx to serve a static webpage.
#        * Ensure the necessary directories are present for the webpage.
#        * Copy a sample index.html to the appropriate directory on the server.
---
# tasks file for nginx_setup
